//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akropole.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flat()
        {
            this.Rent = new HashSet<Rent>();
        }
    
        public int id { get; set; }
        public Nullable<int> idBuilding { get; set; }
        public Nullable<int> myFlor { get; set; }
        public Nullable<int> idViewType { get; set; }
        public Nullable<int> idRoomsCount { get; set; }
        public Nullable<int> idBathType { get; set; }
        public Nullable<int> bathCount { get; set; }
        public Nullable<bool> condition { get; set; }
        public Nullable<decimal> cadastPrice { get; set; }
        public Nullable<decimal> marketPrice { get; set; }
        public Nullable<decimal> rentPrice { get; set; }
        public Nullable<int> idStatus { get; set; }
    
        public virtual BathType BathType { get; set; }
        public virtual Building Building { get; set; }
        public virtual RoomsCount RoomsCount { get; set; }
        public virtual Status Status { get; set; }
        public virtual ViewType ViewType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent> Rent { get; set; }
    }
}
